import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer";

import ModalProvider from "@/providers/modal-provider";
import MainNavbar from "@/components/root-navbar";

const font = Urbanist({
  subsets:['latin'],
})

export const metadata: Metadata = {
  title: "Galaxy Tile and Ceremics",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={font.className}
      >
        <ModalProvider/>
        <MainNavbar/>
          {children}
        <Footer/>
      </body>
    </html>
  );
}
